### ISSUE TITLE
filter_by_count.py does not exist

### ISSUE THREAD

**Issue by pb-jlandolin** [PacificBiosciences/cDNA_primer#14]
Cross-posting this reported issue here:

PacBio support, 

I am helping a postdoc to get pbtranscript-tofu ( 
https://github.com/PacificBiosciences/cDNA_primer/wiki/Setting-up-virtualenv-and-installing-pbtranscript-tofu) 
installed on our cluster. In the installation, the make process dies with 
the following error: 

error: file 
'/ycga-ba/home/jsi3/pacbioAlex/cDNA_primer/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/filter_by_count.py' 
does not exist 
make: *** [build] Error 1 

I checked the GitHub repo (https://github.com/PacificBiosciences/cDNA_primer) 
and found that the file doesn't exist in the repository. Should the file be 
there or should have been created at some point earlier in the build 
process? 

Thanks, 
Jason

**Comment by Magdoll** [comment]
My bad! I just cheked in the file "filter_by_count.py".

**Comment by 52teth** [comment]
The same for me. When I Setting up virtualenv and installing pbtranscript tofu, the error occurred in the make step:
$ /opt/smrtanalysis/smrtcmds/bin/smrtshell
$ source $VENV_TOFU/bin/activate
(VENV_TOFU)$ git clone git@github.com:PacificBiosciences/cDNA_primer.git
(VENV_TOFU)$ cd cDNA_primer/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/branch/C/
(VENV_TOFU)$ python setup2.py build_ext --inplace
(VENV_TOFU)$ cd ../../../../
(VENV_TOFU)$ make
.....
copying and adjusting pbtools/pbtranscript/tofu_wrap.py -> build/scripts-2.7
error: file '/share/nas3/tengh/SMRT/software/TOFU/cDNA_primer/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/filter_by_count.py' does not exist
How can I get the filter_by_count.py?

**Comment by Magdoll** [comment]
Hi,
Did you just do the git clone? I checked in the missing filter_by_count.py 12 days ago. 

I just repeated the commands you showed above and I did not encounter the error because filter_by_count.py is there.

Please try to check out the latest ToFU version. Thanks!

--Liz

**Comment by 52teth** [comment]
Thanks a lot, Liz!  My fault! I  got the clone 18 days ago.
Then I try to install it again with the current version, but another error occured. When I go to the step 'python setup2.py build_ext --inplace' in the installation of tofu, the following error occured: 
running build_ext
skipping 'c_branch.c' Cython extension (up-to-date)
building 'c_branch' extension
gcc -pthread -fno-strict-aliasing -fPIC -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/share/nas2/genome/biosoft/smrtanalysis/2.3.0/smrtanalysis/current/redist/python2.7/include/python2.7 -c c_branch.c -o build/temp.linux-x86_64-2.7/c_branch.o
c_branch.c:346:31: error: numpy/arrayobject.h: No such file or directory
c_branch.c:347:31: error: numpy/ufuncobject.h: No such file or directory
...
error: command 'gcc' failed with exit status 1

Is there something with my virtual Python environment? Can you give any advice for my problem?
Or something wrong with my bx-python modules installation? Here is the installation information:
 Downloading bx-python-0.7.3.tar.gz (949kB): 949kB downloaded
  Running setup.py (path:/share/nas3/tengh/software/python_virtualenv/build/bx-python/setup.py) egg_info for package bx-python
    no previously-included directories found matching 'doc/.build'
   Installed /share/nas3/tengh/software/python_virtualenv/build/bx-python/nose-1.3.7-py2.7.egg
    warning: no files found matching 'distribute_setup.py'
Installing collected packages: bx-python
  Running setup.py install for bx-python
    skipping 'lib/bx/bitset.c' Cython extension (up-to-date)
    building 'bx.bitset' extension
.....
Successfully installed bx-python
Cleaning up...
Thanks a lot!

**Comment by 52teth** [comment]
Thanks a  lot! It works now O(∩_∩)O~
