### ISSUE TITLE
P_IsoSeqCluster/cluster OSError: [Errno 2] No such file or directory: '..data/clusterOutDir/scripts/gcon_test_dir/g_consensus.fa'

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#18]
when I use the follwing cmd to do my Isoseq work with SGE:
         smrtpipe.py --params=settings.xml xml:cfg/input.xml 
the following error occurs:

[ERROR] 2015-11-26 01:14:47,115 [smrtpipe.status refreshTargets 413] *** Failed task task://Anonymous/P_IsoSeqC
luster/cluster
[INFO] 2015-11-26 01:14:47,116 [smrtpipe.status execute 627] Found 1 failed tasks.
[INFO] 2015-11-26 01:14:47,116 [smrtpipe.status execute 629] task cluster FAILED
[ERROR] 2015-11-26 01:14:47,582 [SMRTpipe.SmrtPipeMain run 608] SmrtExit task://Anonymous/P_IsoSeqCluster/cluster Failed
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 571, in run
    self._runTasks(pModules)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/SmrtPipeMain.py", line 300, in _runTasks
    workflow.execute()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/SMRTpipe/engine/SmrtPipeWorkflow.py", line 640, in execute
    raise SmrtExit(str(e))
SmrtExit: SmrtExit task://Anonymous/P_IsoSeqCluster/cluster Failed
[ERROR] 2015-11-26 01:14:47,583 [SMRTpipe.SmrtPipeMain exit 690] SmrtExit task://Anonymous/P_IsoSeqCluster/cluster Failed
[INFO] 2015-11-26 01:14:47,584 [SMRTpipe.SmrtPipeMain exit 692] Beginning exit process

Then i checked the P_IsoSeqCluster/cluster.log, then the following error information is given:
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/analysis/bin/pbtranscript.py", line 146, in run
    obj.run()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 245, in run
    fastq_filename=first_split_fq)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 95, in __init__
    sanity_check_sge(self.script_dir)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceUtils.py", line 81, in sanity_check_sge
    if not filecmp.cmp(consensusFa, GCON_OUT_FA):
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/filecmp.py", line 42, in cmp
    s1 = _sig(os.stat(f1))
OSError: [Errno 2] No such file or directory: '/lustre/tengh/SMRT/test_TOFU_v2/result/BasicAnalysis/MCF1/data/clusterOutDir/scripts/gcon_test_dir/g_consensus.fa'

I have checked the dir '/lustre/tengh/SMRT/test_TOFU_v2/result/BasicAnalysis/MCF1/data/clusterOutDir/scripts/gcon_test_dir/', only gcon_in.fa can be found. So what's the matter with my job submit? What can I do with this problem?

By the way, I have tested a job without the use of SGE, and it has completed successfull. So I can make sure that there's somthing with my SGE. So what can I with it?

Thanks a lot for any adviceO(∩_∩)O

**Comment by bowhan** [comment]
The problem is that the test job running `ice_pbdagcon.py` failed to produce the expected output file `g_consensus.fa`. 
To help us debug, can you please try the following from your head node?
```bash
# invoke smrtshell to load smrt analysis environment (double-check the path)
/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/smrtcmds/bin/smrtshell
# check SGE
qstat
# if errors such as "Unable to initialize environment because of error: Please set the environment variable SGE_ROOT" occurs, try re-export this variable
export SGE_ROOT=XXX # you can probably find its value BEFORE you invoke smrtshell
# after you have SGE available, go to the job folder
cd /lustre/tengh/SMRT/test_TOFU_v2/result/BasicAnalysis/MCF1/data/clusterOutDir/scripts/
# confirm that you have a test.sh file, and submit the test job manually
qsub -sync y -cwd -S /bin/bash -V -e stderr1 -o stdout1 test.sh
# you should see something like: Your job 99999 ("test.sh") has been submitted
# if it fails, check files stdout1, stderr1, and use qstat -j to find out what was wrong
qstat -j 99999 # you should have a different jobid
```
Thank you!
Bo

**Comment by 52teth** [comment]
@bowhan thanks a lot. But it shows  qstat: command not found

here is the cmd:
[tengh@compute-0-227 P_IsoSeqCluster]$ /share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/smrtcmds/bin/smrtshell
(smrtshell-2.3.0) [tengh@compute-0-227 P_IsoSeqCluster]$ qstat
bash: qstat: command not found

**Comment by bowhan** [comment]
You need to `export SGE_ROOT=XXX`. You should have its value before you invoke `smrtshell`.

**Comment by 52teth** [comment]
what does the head node mean? Is it the submmit node that I run the smrtpipe.py cmd? Or the head node of my SGE cluster? And how can i

**Comment by 52teth** [comment]
In addtion, when I  ' export SGE_ROOT=XXX  ' before invoke smrtshell, the 'command not found' error still exits. By the way, the qstat commnad can be found before invoke smrtshell. So I tried  ' export SGE_ROOT=XXX  ' after invoke smrtshell, and the error is still there.

**Comment by bowhan** [comment]
Sorry that I didn't explain it clearly enough...
When you invoke `smrtshell`, it wipes off most of your environmental variables, including `SGE_ROOT` and others, which makes SGE unavailable. In order to use `qsub` to submit the `test.sh` manually, you need to fix this, by telling the shell where to find SGE commands. 
I was asking you to find out the value of `SGE_ROOT` (by `echo $SGE_ROOT`) and the path to `qstat` and others (by `which qstat`) BEFORE invoking `smrtshell` so that you can get them back under smrtshell (by `export SGE_ROOT=/path/to/sge_root` and `export PATH=/path/to/qstat/:${PATH}`). So please don't not do `export SGE_ROOT=XXX` before you invoke `smrtshell`, it might mess up with your normal setting. And 'XXX' here is just a representation, please replace it with the true value of `SGE_ROOT` after you find it out.

You might want to open a new terminal and login to your hpc (aka the head node) and start fresh.

**Comment by 52teth** [comment]
what does the head node mean? Is it the submmit node that I run the smrtpipe.py cmd? Or the head node of my SGE cluster? And how can I find my head node?

**Comment by 52teth** [comment]
I log in the node that setup the SMRTAnalysis, and another error informed: 
(smrtshell-2.3.0) [tengh@login-0-1 ~]$ export SGE_ROOT=/opt/gridengine
(smrtshell-2.3.0) [tengh@login-0-1 ~]$ qstat
bash: qstat: command not found
(smrtshell-2.3.0) [tengh@login-0-1 ~]$ /opt/gridengine/bin/linux-x64/qstat
error: commlib error: got select error (Connection refused)
error: unable to send message to qmaster using port 6444 on host "cluster.local": got send error

**Comment by bowhan** [comment]
head node is the node to submit jobs, as opposed to execution nodes, which runs the jobs.
Anyway, what I really meant is the node where you execute this command `smrtpipe.py --params=settings.xml xml:cfg/input.xml` in the first place. 
Before invoking `smrtshell`, are you able to do `qstat` or `qlogin` successfully at this node? Because based on the error message, that node does not have SGE running, or does not have access to it. The node running smrtanalysis should be able to submit jobs, otherwise you cannot expect it to use SGE.

**Comment by 52teth** [comment]
Before invoking smrtshell, I can submit the job successfully by qsub, and qstat is ok. So there is something error with my SGE settings when setup Smrtanalysis software, is there any simple way to solve this problem? Or I have to setup again?

**Comment by bowhan** [comment]
If you can submit job outside of smrtshell, can you please try this
```bash
cd /lustre/tengh/SMRT/test_TOFU_v2/result/BasicAnalysis/MCF1/data/clusterOutDir/scripts/
```
then create a bash file, example `test_wrap.sh` with the following content
```bash
#! /bin/bash -x
/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/smrtcmds/bin/smrtshell test.sh
```
then
```bash
chmod 755 test_wrap.sh
qsub -sync y -cwd -S /bin/bash -V -e stderr1 -o stdout1 test_wrap.sh 
```
Then can you please let me know all the messages as well as the contents of `stdout1` and `stdout1`?

**Comment by 52teth** [comment]
I firt submit at the compute node, but error information is given: 
[tengh@compute-0-227 scripts]$ qsub -sync y -cwd -S /bin/bash -V -e stderr1 -o stdout1 test_wrap.sh
Unable to run job: denied: host "compute-0-227.local" is no submit host.
Exiting.
Since submit qsub job is not permittted in our compute node , so I change to the login node, here is the message: 
[tengh@login-0-4 scripts]$ qsub -sync y -cwd -S /bin/bash -V -e stderr1 -o stdout1 test_wrap.sh
Your job 5352747 ("test_wrap.sh") has been submitted

**Comment by 52teth** [comment]
But when I invoke in smrtshell , the qstat and qsub is not permitted:
[tengh@login-0-4 scripts]$  /share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/smrtcmds/bin/smrtshell
(smrtshell-2.3.0) [tengh@login-0-4 scripts]$ export SGE_ROOT=/opt/gridengine
(smrtshell-2.3.0) [tengh@login-0-4 scripts]$ /opt/gridengine/bin/linux-x64/qstat
error: commlib error: got select error (Connection refused)
error: unable to send message to qmaster using port 6444 on host "cluster.local": got send error

**Comment by bowhan** [comment]
Did you run `smrtpipe.py --params=settings.xml xml:cfg/input.xml` on the "compute node" or the "login node"?

**Comment by 52teth** [comment]
I have run on both compute node and login node, but the sam error occurs. So, I don't know how to deal with it::>_<::

**Comment by bowhan** [comment]
What version of `smrtanalysis` do you have? 
```bash
# version
/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/admin/bin/buildinfo --rel_versionnum
# patch
/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/admin/bin/buildinfo --patch-level
```
The most recent version is v2.3.0 Patch 5. If this is not what you have, can you try to update it to see if it can fix your problem? You can obtain it [here](http://www.pacb.com/support/software-downloads/) and the instruction is [here](http://www.pacb.com/wp-content/uploads/2015/09/SMRT-Analysis-Software-Installation-v2.3.0.pdf).

**Comment by 52teth** [comment]
I have updated our SMRT Analysis with patch5, but when I start my job with SMRT portal again, the 'OSError: [Errno 12] Cannot allocate memory' error occurs. Here is the details:

**********************************************************
2015-12-12 18:55:00,862 INFO [main] Multi-threaded. Input: /share/basecall2/data/Smrt_Portal_result/jobs/016/016480/data/clusterOutDir/tmp/0/c8633/g_consensus.saln, Threads: 8
[INFO] 2015-12-12T18:55:00 [blasr] started.
[INFO] 2015-12-12T18:55:00 [blasr] ended.
[INFO] 2015-12-12T18:55:01 [blasr] started.
2015-12-12 18:55:00,821 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/analysis/bin/pbtranscript.py", line 146, in run
    obj.run()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 248, in run
    self.icec.run()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1361, in run
    self.keep_adding_files(sizes=sizes)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1229, in keep_adding_files
    self.run_for_new_batch()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1178, in run_for_new_batch
    self.run_til_end(1)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 933, in run_til_end
    self.run_gcon_parallel(self.changes)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 445, in run_gcon_parallel
    self.run_gcon_parallel_helper(cids)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 598, in run_gcon_parallel_helper
    rets = pool.map(runConsensus, jobs)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
OSError: [Errno 12] Cannot allocate memory
[INFO] 2015-12-12T18:55:01 [blasr] ended.
[INFO] 2015-12-12T18:55:01 [blasr] started.
[INFO] 2015-12-12T18:55:01 [blasr] started.
[INFO] 2015-12-12T18:55:01 [blasr] ended.
[INFO] 2015-12-12T18:55:01 [blasr] ended.
[INFO] 2015-12-12T18:55:01 [blasr] ended.
Exception in thread Thread-344 (most likely raised during interpreter shutdown):
/opt/gridengine/default/spool/compute-0-166/job_scripts/8375025: line 100: 64596 Segmentation fault      (core dumped) pbtranscript.py -v cluster --bas_fofn /share/basecall2/data/Smrt_Portal_result/jobs/016/016480/input.fofn --ccs_fofn /share/basecall2/data/Smrt_Portal_result/jobs/016/016480/reads_of_insert.fofn -d /share/basecall2/data/Smrt_Portal_result/jobs/016/016480/data/clusterOutDir --blasr_nproc 23 --unique_id 16480 --cDNA_size between1k2k --report=/share/basecall2/data/Smrt_Portal_result/jobs/016/016480/data/isoseq_cluster_info.csv --summary=/share/basecall2/data/Smrt_Portal_result/jobs/016/016480/data/cluster_summary.txt --nfl_fa=/share/basecall2/data/Smrt_Portal_result/jobs/016/016480/data/isoseq_nfl.fasta /share/basecall2/data/Smrt_Portal_result/jobs/016/016480/data/isoseq_flnc.fasta /share/basecall2/data/Smrt_Portal_result/jobs/016/016480/data/consensus_isoforms.fasta
# Writing stdout and stderr from Popen:
Your job 8375025 ("Iclu016480") has been submitted
Job 8375025 exited with exit code 139.
*************************************************
 It seems the memory is not enoug at my compute node. So what should I do with this problem? should I change the qsub parameter [ -q general.q] to [ -q middle.q] ？

**Comment by bowhan** [comment]
Yes, please edit both `start.tmpl ` and `interactive.tmpl` files to reflect the queue to use in smrtanalysis. 
If you run `pbtranscript.py` or `tofu` directly on the command line, please do the switch using option `--sge_queue`.

**Comment by iggyB** [comment]
Hej bowhan,

Had similar issue long time ago, but had no time to solve it... Anyhow, if I submit the test_wrap.sh outside smrtshell and it runs without problem, what does it mean? Is env not correctly exported to the nodes?

**Comment by bowhan** [comment]
@iggyB Yes, it means the environmental variables are not exported correctly. In that case, just wrap the whole command in `smrtshell` and submit a jobs with something like:
```bash
smrtshell -c "pbtranscript.py ..."
```

**Comment by iggyB** [comment]
Jap, I can do that if I run it from CLI.

Any ideas/tips how to fix this in SMRT portal?

We were going around the problem by not running RS_IsoSeq clustering with SGE enabled, but on a bigger data sets would be nice to speed up things.

**Comment by bowhan** [comment]
Probably suggests some issue in your SGE setting. Were you manage to run other protocols (non Iso-Seq) with SGE enabled?

**Comment by iggyB** [comment]
We have been using SMRT portal since the beginning, we have our own SGE cluster. Everything else runs smooth. SMRT portal is up to date. 

We didn't have that many IsoSeq projects previously, but now more and more comes in. So would be nice to fix this issue.

**Comment by bowhan** [comment]
In the jobview of smrtportal, there is a link to download `Tech Support Files`, can you please send it to  bhan`at`pacificbiosciences.com and support`at`pacificbiosciences.com?

**Comment by iggyB** [comment]
Done
