### ISSUE TITLE
Issue with fusion_finder

### ISSUE THREAD

**Issue by chetanya** [PacificBiosciences/cDNA_primer#2]
Hi Liz,

I would like to use TOFU’s fusion_finder.py script to detect chimeric fusions in my IsoSeq datasets. Unfortunately, I keep running into the following error:

```
interactive2:PacBio pandyc01$ fusion_finder.py --input ../FASTA/13021_5671N_1to2k_IsoSeqNew_high_qv_consensus_isoforms.fasta -s test_blasr_sorted.sam -o fusion_output
Traceback (most recent call last):
File "/hpc/packages/minerva-common/pacbio/bin/fusion_finder.py", line 5, in <module>
pkg_resources.run_script('pbtools.pbtranscript==0.3.tofu', 'fusion_finder.py')
File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 528, in run_script
File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1394, in run_script
File "/hpc/packages/minerva-common/pacbio/lib/python2.7/site-packages/pbtools.pbtranscript-0.3.tofu-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 311, in <module>
fusion_main(args.input, args.sam, args.prefix, is_fq=args.fq, allow_extra_5_exons=args.allow_extra_5exon, skip_5_exon_alt=False, prefix_dict_pickle_filename=args.prefix_dict_pickle_filename)
File "/hpc/packages/minerva-common/pacbio/lib/python2.7/site-packages/pbtools.pbtranscript-0.3.tofu-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 229, in fusion_main
check_ids_unique(fa_or_fq_filename, is_fq=is_fq)
File "/hpc/packages/minerva-common/pacbio/lib/python2.7/site-packages/pbtools.pbtranscript-0.3.tofu-py2.7-linux-x86_64.egg/pbtools/pbtranscript/Utils.py", line 23, in check_ids_unique
if r.id in seen:
AttributeError: 'FastaRecord' object has no attribute ‘id'
```

From what I understand, this error is coming from the fact that "fusion_finder.py" is trying to use an attribute that is not even exist in the imported package ("pbcore"). The requirement says, it requires pbcore >= 0.6.3 and we have pbcore/0.8.5 installed on our cluster. I don't know what version of "pbcore" was used to build the current version.

I would really appreciate your help in solving this issue. Look forward to hearing from you.

Best,
Chetanya

**Comment by Magdoll** [comment]
Hi Chetanya,

I think I may need to up the minimum pbcore version required. Currently TOFU is meant to work with SMRTAnalysis 2.3's pbcore (which is 0.9.1).

I can also try to patch this error, but I am a little worried older versions of pbcore (0.8.5, your version) may have other obsolete features that I was not aware of.

There are a few ways to go about this. How difficult would it be for you to upgrade your SMRTAnalysis to the latest patched version? Among other things, this would eliminate other potential bugs that may come further down the road.

The instructions for patching 2.3 are embedded in the regular install instructions and can be found here:
https://github.com/PacificBiosciences/SMRT-Analysis/wiki/SMRT-Analysis-Software-Installation-v2.3.0#patch-summary
where the patch file is listed above in that document and can be downloaded from:
https://s3.amazonaws.com/files.pacb.com/software/smrtanalysis/2.3.0/smrtanalysis-patch_2.3.0.140936.p2.run

If upgrading is not an option, I can patch just this error and see if this is the only difference between the older and new versions of pbcore.

Thanks!
--LIz

**Comment by Magdoll** [comment]
Also, here is a test to make sure pbcore FastaRecord is agreeing with the TOFU usage:

>>> import pbcore
>>> pbcore.__VERSION__
Out[11]: '0.9.1'
>>> from pbcore.io import FastaRecord
>>> r = FastaRecord(name='test', sequence='AAAT')
>>> r.id, r.name, r.sequence
Out[14]: ('test', 'test', 'AAAT')

If all of these work, your pbcore should work.

**Comment by adeslatt** [comment]
FYI.  pbcore 0.9.1 is available as a release on github.

wget --trust-server-names https://github.com/PacificBiosciences/pbcore/archive/0.9.1.tar.gz

just rename it to pbcore.0.9.1.tar.gz when you download it (not necessary but makes your life easier if you have to come back to it).

**Comment by chetanya** [comment]
Thanks Liz and @adeslatt ! I'll upgrade to pbcore version 0.9.1 and report back.
