### ISSUE TITLE
Does the tofu_wrap.py  can deal with data without reference genome?

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#23]
I have got the  sample sequencing data using SMRT  RNA sequencing tech. I want to use the  tofu_wrap.py  to analysis.The sample doesn't have reference genome yet.  So does tofu_wrap can deal with this no reference genome data?

**Comment by bowhan** [comment]
Yes, it can. 
Supplying a gmap index of the genome is optional. Please read more on [this wiki page](https://github.com/PacificBiosciences/cDNA_primer/wiki/tofu-Tutorial-%232.-Isoform-level-clustering-%28ICE-and-Quiver%29).

**Comment by 52teth** [comment]
Yes  I have look through the wiki. Here is the description for extra parameters than  pbtranscript.py :
• --gmap_db : must be given to direct to the GMAP genome index directory (in gmap, this would be the  -D  option)
• --gmap_name : must be given for the GMAP DB name (in gmap, this would be the  -d  option)
And in the tofo_wrap.py script , there is SANITY CHECKS between line 237 to line 250:
    # #################################################################
    # SANITY CHECKS
    if not args.quiver:
        print >> sys.stderr, "--quiver must be turned on for tofu_wrap. Quit."
        sys.exit(-1)
    if args.nfl_fa is None:
        print >> sys.stderr, "--nfl_fa must be provided for tofu_wrap. Quit."
        sys.exit(-1)
    if not os.path.exists(args.gmap_db):
        print >> sys.stderr, "GMAP DB location not valid: {0}. Quit.".format(args.gmap_db)
        sys.exit(-1)
    if not os.path.exists(os.path.join(args.gmap_db, args.gmap_name)):
        print >> sys.stderr, "GMAP name not valid: {0}. Quit.".format(args.gmap_name)
        sys.exit(-1)
It seems the tofu_wrap.py can only used with gmap data.
Thanks a lot for your reply.

**Comment by bowhan** [comment]
You can either provide an irrelevant but genuine gmap index and ignore the corresponding outputs,
or feed two random directories to bypass the sanity checks and comment out the following lines in `tofu_wrap.py` to suppress running of those steps.
```python
    # (5) collapse quivered HQ results
    collapse_prefix_hq = run_collapse_sam(hq_filename, args.gmap_db, args.gmap_name, cpus=args.blasr_nproc, max_fuzzy_junction=args.max_fuzzy_junction)
    # (6) make abundance 
    get_abundance(collapse_prefix_hq, hq_pre_dict, collapse_prefix_hq)
    # (7) run filtering
    run_filtering_by_count(collapse_prefix_hq, collapse_prefix_hq+'.min_fl_2', min_count=2)
```

**Comment by 52teth** [comment]
@bowhan Thanks a lot for your reply. I'll have a try.

**Comment by Magdoll** [comment]
Hi,
Just confirming what Bo says. You can either just provide a useless reference (often I just have it default to the human genome), comment/remove those two lines, or just ignore those options and let ToFU "softly fail". Since GMAP alignment and filtering is the very last step in ToFU, having it fail simply because there is no reference or can't find a reference is OK.
