### ISSUE TITLE
Can I use smrtpipe.py to continue my job?

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#24]
I have run my Isoseq analysis using smrtpipe.py command. But it stopped at cluster anlalysis for my SGE not stable. Now I want to continue the job again. So how can I restart it? 

Thanks a lot for reply!

**Comment by Magdoll** [comment]
Where was it last stopped? Did you complete ICE? (you can tell if clusterOut/output/final.consensus.fasta) exists. What is the last line in clusterOut/log/Cluster.log?

There are very easy entry points to post-ICE, which is just running the Quiver portion: https://github.com/PacificBiosciences/cDNA_primer/wiki/RS_IsoSeq-%28v2.3%29-Optional%3A-Additional-Entry-Points-in-%60cluster%60

It's also possible to re-start a ICE job from the middle but a little trickier and not as well documented.
