### ISSUE TITLE
ImportError: No module named modified_bx_intervals.intersection_unique

### ISSUE THREAD

**Issue by Magdoll** [PacificBiosciences/cDNA_primer#3]
When running collapse_isoforms_by_sam.py, the following import error happens for *some* but not all of the systems:

(tofu_17MAR15)(smrtshell-2.3.0) [nandit@gemini T3-6Kb_QV]$  collapse_isoforms_by_sam.py --input /projects/nandit/Bp_PacBio_sequencing/ISOSEQ/25SMRT_CELL_UPDATED_PIPELINE/T3-6Kb/016786/data/polished_high_qv_consensus_isoforms.fasta -s T3-6Kb_QV_Aligned.out.sorted.sam --dun-merge-5-shorter -o T3-6Kb_QV.nomerge5
Traceback (most recent call last):
  File "/home/nandit/tofu_17MAR15/bin/collapse_isoforms_by_sam.py", line 5, in <module>
    pkg_resources.run_script('pbtools.pbtranscript==0.4.0', 'collapse_isoforms_by_sam.py')
  File "/home/nandit/tofu_17MAR15/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/nandit/tofu_17MAR15/lib/python2.7/site-packages/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/home/nandit/tofu_17MAR15/lib/python2.7/site-packages/pbtools.pbtranscript-0.4.0-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 42, in <module>
    from pbtools.pbtranscript.branch import branch_simple2
  File "/home/nandit/tofu_17MAR15/lib/python2.7/site-packages/pbtools.pbtranscript-0.4.0-py2.7-linux-x86_64.egg/pbtools/pbtranscript/branch/branch_simple2.py", line 4, in <module>
    import pbtools.pbtranscript.c_branch as c_branch
  File "c_branch.pyx", line 4, in init c_branch (pbtools/pbtranscript/branch/C/c_branch.c:5027)
ImportError: No module named modified_bx_intervals.intersection_unique

This is caused by the subfolder pbtools/pbtranscript/modified_bx_intervals not having the file `__init__.py` that is required to make python understand that it is a package.

Two things should be attempted in order to try to fix this:

First, re-install TOFU (version 0.4.1 and up) by doing the following ([full tutorial here](https://github.com/PacificBiosciences/cDNA_primer/wiki/Setting-up-virtualenv-and-installing-pbtranscript-tofu))
```
(VENV_TOFU)$ git clone git@github.com:PacificBiosciences/cDNA_primer.git
(VENV_TOFU)$ cd cDNA_primer/pbtranscript-tofu/pbtools/pbtranscript/branch/C/
(VENV_TOFU)$ python setup2.py build_ext --inplace
(VENV_TOFU)$ cd ../../../../
(VENV_TOFU)$ make
```

Then try running:
```
(VENV_TOFU)$ cd $HOME
(VENV_TOFU)$ collapse_isoforms_by_sam.py --help
```

If the same import error happens, locate the actual installed lib directory in the virtual environment. In the case of the example error message above, go to: `/home/nandit/tofu_17MAR15/lib/python2.7/site-packages/pbtools.pbtranscript-0.4.0-py2.7-linux-x86_64.egg/pbtools/pbtranscript/modified_bx_intervals` and check that two files exist:

`intersection_unique.so`
and
`__init__.py`

If `intersection_unique.so` does not exist, go back to the downloaded GitHub code and try the installation again. If `__init__.py` does not exist, simply type:

```
touch __init__.py
```

to create this empty file.

Now the import error should be gone.

Unfortunately this `touch` fix is transient. Every time a new virtual environment is created or a new TOFU is installed, this has to be repeated.

I will try to find a permanent solution in the meantime.

**Comment by Ginsea** [comment]
I finished all above operations, while errors also existed

**Comment by josator** [comment]
This information should appear in the wiki, so people does not lose time with it:

https://github.com/PacificBiosciences/cDNA_primer/wiki/Setting-up-virtualenv-and-installing-pbtranscript-tofu#importing-smrt-analysis

**Comment by Magdoll** [comment]
Thanks. I have done so.

**Comment by josator** [comment]
Thank you very much.
