### ISSUE TITLE
How can I continue my quiver work in 'pbtranscript.py  cluster' job?

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#35]
Hi pacbio,
I have run my work to do the cluster and quiver using the following command:
`pbtranscript.py  cluster   --bas_fofn input.fofn --ccs_fofn reads_of_insert.fofn -d  data/clusterOutDir.bak --blasr_nproc 40 --quiver  --quiver_nproc 20 --cDNA_size between1k2k --report=data/isoseq_cluster_info2.csv  --summary=data/cluster_summary2.txt --nfl_fa=data/isoseq_nfl.fasta data/isoseq_flnc.fasta data/consensus_isoforms2.fasta`
But after about half of the quiver job, I stoped the jobs by mistake. Since the cluster and quiver job is quite time consuming,  I am confused is there any method to continue the quiver jobs without restart the whole ICE cluster jobs and quiver？
Thanks a lot!

**Comment by Magdoll** [comment]
Hi,

Yes there is a way to start just the Quiver portion.

This [tutorial](https://github.com/PacificBiosciences/cDNA_primer/wiki/RS_IsoSeq-%28v2.3%29-Optional%3A-Additional-Entry-Points-in-%60cluster%60) introduces alternative entry points to the ICE+Quiver process.

If you already have ICE finished, you should have something like:

clusterOut/output/final.consensus.fasta
clusterOut/output/final.pickle

Now, the next step is called "Polish" which has two sub-steps. One is IcePartial, one is IceQuiver.

You can figure out whether you already have IcePartial finished. If it is finished, you should see a file:

clusterOut/output/map_noFL/all.nfl.pickle (or something similar)

If IcePartial is done, you only need to run Quiver:

```
ice_quiver.py all --bas_fofn input.fofn --fasta_fofn input.fasta.fofn --use_sge --max_sge_jobs 120 --blasr_nproc 20 --quiver_nproc 8 clusterOut/
```

Monitor that all the Quiver jobs are done by looking at log/IceQuiver.log and `qstat`. When all jobs are finished, you can collect the result:

```
ice_quiver.py postprocess clusterOut/ --use_sge
```

**Comment by 52teth** [comment]
Thanks a lot! I get it!
