### ISSUE TITLE
fusion_finder.py AssertionError

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#39]
when I use the fusion_finder.py in TOFU to find fusion gene by the following command: 
fusion_finder.py --input all_sizes.sorted.5merge.collapsed.rep.fa -s Fusion_finder.sorted2.sam -o fusion >fusion.log 
The following error comes out: 
Traceback (most recent call last):
  File "/share/nas1/tengh/software/venv_TOFU/bin/fusion_finder.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbtools.pbtranscript==2.2.3', 'fusion_finder.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 719, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1504, in run_script
  File "/share/nas1/tengh/software/venv_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 389, in <module>
    min_dist_between_loci=args.min_dist_between_loci)
  File "/share/nas1/tengh/software/venv_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 339, in fusion_main
    assert pbid1.split('.')[1] == pbid2.split('.')[1]
AssertionError
I have checked my branch_tmp.group.txt file, there is a lot PBfusion including more than two fusion gene: 
PBfusion.6.0    PB.6781.3|Chr6:428068351-428073000(+)|i2HQ_B377|c21788/f1p0/4320,PB.6781.4|Chr6:428068358-428072943(+)|i2HQ_B377|c3974/f2p0/4410,PB.502.1|Chr1:298449476-298454030(-)|i2LQ_B377|c31473/f1p0/4257
PBfusion.6.1    PB.6781.3|Chr6:428068351-428073000(+)|i2HQ_B377|c21788/f1p0/4320,PB.6781.4|Chr6:428068358-428072943(+)|i2HQ_B377|c3974/f2p0/4410,PB.502.1|Chr1:298449476-298454030(-)|i2LQ_B377|c31473/f1p0/4257
PBfusion.6.2    PB.6781.4|Chr6:428068358-428072943(+)|i2HQ_B377|c3974/f2p0/4410
PBfusion.6.3    PB.6781.4|Chr6:428068358-428072943(+)|i2HQ_B377|c3974/f2p0/4410
here is the gmap alignment result(SAM format): 
PB.6781.3|Chr6:428068351-428073000(+)|i2HQ_B377|c21788/f1p0/4320	16	Chr1	298449371	0	866M1D619M1I609M1D200M1D26M150N295M82N188M1D17M78N275M1D356M1D95M1D27M1D143M2D209M1D152M1D6M1D89M1D12M1D13M1D9M1D43M1D36M1D34M	* ...
PB.6781.3|Chr6:428068351-428073000(+)|i2HQ_B377|c21788/f1p0/4320	16	Chr1	525509417	0	866M1D619M1I609M1D200M1D26M150N295M82N188M1D17M78N275M1D356M1D95M1D27M1D143M2D209M1D152M1D6M1D89M1D12M1D13M1D9M1D43M1D36M1D34M	* ...
PB.6781.3|Chr6:428068351-428073000(+)|i2HQ_B377|c21788/f1p0/4320	0	Chr6	428068351	40	69M1D42M1D6M1D16M1D10M1D92M1D5M1D152M1D210M1D142M1D27M1D97M2D354M1D277M78N14M1D191M82N295M150N23M1D199M1D674M1D557M1D4M1D864M	* ...
PB.6781.4|Chr6:428068358-428072943(+)|i2HQ_B377|c3974/f2p0/4410	16	Chr1	298449428	0	237M1D571M1D355M1D72M1D124M1I66M1I24M1D50M1D195M1D5M1D532M1D26M150N23M1D48M1D107M1D755M1D264M1D91M1D123M1D21M1D121M1D141M1D15M1D138M1D163M2D25M1D13M1D76M1D27M	* ...
PB.6781.4|Chr6:428068358-428072943(+)|i2HQ_B377|c3974/f2p0/4410	16	Chr1	525509474	0	237M1D571M1D355M1D72M1D124M1I66M1I24M1D50M1D195M1D5M1D532M1D26M150N23M1D48M1D107M1D755M1D264M1D91M1D123M1D21M1D121M1D141M1D15M1D138M1D163M2D25M1D13M1D76M1D27M	* ...
PB.6781.4|Chr6:428068358-428072943(+)|i2HQ_B377|c3974/f2p0/4410	0	Chr3	682267518	0	27M1D74M1D10M1D27M2D164M1D60M3I74M1D16M1D108M14I21M1D118M1D22M1D125M2D88M1D104M1D161M1D755M1D107M1D49M1D24M150N23M1D533M1D6M1D195M1D50M1D214M1D72M1D26M1D330M1D4M1D568M1D238M	* ...
PB.6781.4|Chr6:428068358-428072943(+)|i2HQ_B377|c3974/f2p0/4410	0	Chr6	428068358	40	101M1D10M1D27M2D164M1D137M1D16M1D261M1D22M1D125M2D88M1D265M1D755M1D107M1D49M1D24M150N23M1D533M1D6M1D195M1D50M1D214M1D72M1D356M1D4M1D568M1D238M	*

So is there any advice for  my problem? How can I deal with it?
Thank a lot for any advie.

**Comment by Magdoll** [comment]
It appears that this is a rare case I didn't catch. I thought GMAP would only show chimeras if they are split into two alignments but in this case they were split into 3 or 4 segments so my code is broken because it was only expecting two segments of a chimeric mapping.

I can fix it but I would need the example SAM file to work with to make sure it's corrected. Could you possibly send just the sequence and alignment of PB.6781.3 and PB6781.4 to etseng@pacb.com?

The easiest way to do it woud be:

1. create a fasta file with just the two sequences 
2. re-run GMAP with the same parameters on (1). this should be fast since it's just two sequences.

In this way the GMAP SAM files would have the proper headers.

Thanks,
--Liz

**Comment by 52teth** [comment]
Thank a lot! It really work!
