### ISSUE TITLE
Build output in clone

### ISSUE THREAD

**Issue by rekado** [PacificBiosciences/cDNA_primer#4]
On a clone at commit c7bbd5472 there are a lot of files and directories in `pbtranscript-tofu/pbtranscript/` that probably should not have been committed.  Among them are:

./dist/
./build/
./setuptools_cython-0.2.1-py2.6.egg/
./pbtools.pbtranscript.egg-info
./Cython-0.20.1.tar.gz
./setuptools_cython-0.2.1-py2.7.egg
./setuptools_cython-0.2.1.tar.gz

as well as lots of `*.so` files.

When these files are present the build may fail or runtime errors may appear because the files were not built on the same system.  In my [package recipe for GNU Guix](http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/bioinformatics.scm#n806) I simply deleted all of these files before building.

**Comment by Magdoll** [comment]
Thanks. Indeed I will clean up the .so and the excessive build directories in the next commit. Thanks!
