### ISSUE TITLE
cluster result: HQ isoform +LQ isoform != consensus sequence number?

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#43]
Hi, 
I have used RS_IsoSeq Cluster to run ICE and quiver as 'RS_IsoSeq (v2.3) Optional: Additional Entry Points in `cluster` (https://github.com/PacificBiosciences/cDNA_primer/wiki/RS_IsoSeq-(v2.3)-Optional%3A-Additional-Entry-Points-in-`cluster) intro, but the result shows that the sum of HQ isoforms and LQ isoforms is not equal to the consensus sequence number, I have used this pipline to deal with 5 data set, only 3 of them HQ +LQ=consensus sequences. So is this normal ? Or is there any possible problem with my pipline? 
Thanks for any advice!

**Comment by Magdoll** [comment]
Hi,

Yes, in some cases HQ + LQ < # of consensus. But the difference should be minor.

This has been documented in as ["Not A Bug"](https://github.com/PacificBiosciences/cDNA_primer/issues/10). Please read the issue report. Let me know if you have any further questions.

--Liz
