### ISSUE TITLE
Is there any tools to vaidate the rarefaction for sample data?

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#44]
Hi,
I have read the intro in "Bioinfx study: Sampling depth? Simulated rarefaction curves based on real data(https://github.com/PacificBiosciences/cDNA_primer/wiki/Bioinfx-study:-Sampling-depth%3F-Simulated-rarefaction-curves-based-on-real-data)",  it is really a good way to valiate the sample depth. I am confused is this method have been packaged in any tool? OR can I find the scripts anywhere? I think it will help a lot. 
Thanks a lot for any help?

**Comment by Magdoll** [comment]
Hi,

I am working on getting this to work directly with Iso-Seq cluster output. It is on my ToDO list...

For now, if you want to use it, you have to make the count file yourself. If you had run ToFU you should get a .abundance.txt file from which you can extract the counts. You will also need the length of the isoforms. 

Here's the script:
https://github.com/Magdoll/ICE/blob/master/subsample.py
 
You will need Python 2.x and numpy installed.
 
The way to use it is to create a file with at least the following columns: a unique "pbid" (PB.x.y), "length", and "fl_count". All other columns are optional.
 
An example count file:
https://www.dropbox.com/s/4wtp7aqs1g1l1r0/all_tissues.combined_for_rarefaction.novel_n_known.txt?dl=0
 
Then you call it with:
 
subsample.py <count_filename> --by pbid --range "(1000,2000)"  > output.1to2k.by_pbid.txt
 
or something like that. 
 
This dropbox contains a lot more examples:
https://www.dropbox.com/sh/nc6nhvks28hpm1w/AAA7chjM6kvN8ENmhvUbk2ZGa?dl=0
 
The subfolder "output" contains the output. I just plot it in Excel or R.

**Comment by 52teth** [comment]
Thanks a lot! I will try it later!

**Comment by Magdoll** [comment]
Hi,

The official script and wiki for rarefaction drawing is now available at the [cDNA_Cupcake repo](https://github.com/Magdoll/cDNA_Cupcake/wiki/Annotation-and-Rarefaction-Wiki). 

Closing this issue.
