### ISSUE TITLE
tofu_wrap.py run each size bin in parallel 

### ISSUE THREAD

**Issue by Dongxn** [PacificBiosciences/cDNA_primer#46]
Hi, I am using tofu_wrap.py to do cluster, it is said tofu automatically divide input fasta (usually isoseq_flnc.fasta) by size bins, and I am wondering if totu could run each size bin in parallel after divided?

0to1kb/
1to2kb/
2to3kb/
3to4kb/
4to5kb/
combined/
fasta_fofn_files/

Thanks!

**Comment by Magdoll** [comment]
Yes, there is a way to hack it. 

tofu_wrap.py will automatically generate the bins and also create fasta_fofn_files/. Once the fasta_fofn_files/ have been created, you should see on the command line that it started doing something like:

`running cluster on 0to1kb/`

Once it has gotten to that stage, you can intentionally kill off tofu_wrap. Then, manually run each bin as a separate job using `pbtranscript.py cluster` instead.

An example is:

````
cd 0to1kb/
pbtranscript.py cluster isoseq_flnc.fasta final.consensus.fasta --nfl_fa <path_to>/isoseq_nfl.fasta -d . --ccs_fofn reads_of_insert.fofn  --bas_fofn input.fofn --quiver --use_sge  --max_sge_jobs 40 --blasr_nproc 20 --quiver_nproc 8 --gcon_nproc 8 --sge_queue def66 --fasta_fofn ../fasta_fofn_files/input.fasta.fofn
```

You should have `input.fasta.fofn` already generated in `fasta_fofn_files` which you can have all the independent cluster jobs use. Make sure you have the full path to `isoseq_nfl.fasta`. The file `isoseq_flnc.fasta` should already be generated in each bin separately.

Once all separate cluster jobs are done (completion is marked by the existence of files `all_quivered_hq.100_30_0.99.fasta` in the size bin. You can re-run tofu_wrap.py again from the top directory (where you first ran it). tofu_wrap.py will detect that all size bins have been completed and directly move on to combining the output and putting it into `combined`.

**Comment by Dongxn** [comment]
Thanks Magdoll !
it works :p
