### ISSUE TITLE
command line results is different from SMRT Portal Analysis results for same dataset 

### ISSUE THREAD

**Issue by RobinQi** [PacificBiosciences/cDNA_primer#47]
Hi,
Recently I found that iso-seq results from SMRT portal is a little bit different from command line analysis results even with same parameters. But I can't figure out the reasons. One example is showed as below,
Using SMRT Portal, it give results as the following figure, 
Number of polished high-quality isoforms is 6,154
Number of polished low-quality isoforms is 8,921.
![iso_cluster](https://cloud.githubusercontent.com/assets/6779816/18775193/aa58c658-8192-11e6-914c-bf5a090a86b1.png)
But I use command line to analysis the same dataset with exactly same parameters, it give results as below,
Number of consensus isoforms=15161
Average consensus isoforms read length=6191
Number of polished high-quality isoforms=5321
Number of polished low-quality isoforms=9840
And the command line is,
pbtranscript.py cluster isoseq_flnc.fasta final.consensus.fa --nfl_fa isoseq_nfl.fasta -d ./cluster --ccs_fofn reads_of_insert.fofn --bas_fofn input.fofn --cDNA_size under1k --quiver --blasr_nproc 20 --quiver_nproc 10 --report=./isoseq_cluster_info.csv --summary=./cluster_summary.txt
So, don't know why the high quality isoforms number is different from SMRT Portal results. I am not sure whether the ICE give different results each time.
Can you give me some suggestions?
Thanks.
--Robin

**Comment by ylipacbio** [comment]
Yes, the polished HQ LQ isoforms can be slightly different from run to run even for the same dataset, because different random numbers are generated and used for different runs.

**Comment by RobinQi** [comment]
OK, Thanks.

**Comment by ylipacbio** [comment]
Please first check software versions are identical. 
But more likely the differences are caused because different sets of parameters are used.

You can find which command lines that a SMRTPortal isoseq job has used under its SMRTPortal job directory.

**Comment by ylipacbio** [comment]
The number of consensus isoforms and their average length looks pretty similar to each other.  ICE output looks consistent to me.

The differences in number of HQ/LQ isoforms is likely due to a change in pbtranscript version to me. Once upon a time, we have made the definition of HQ more stringent requiring at least two supportive FLNC reads to call an isoform HQ, which leads to less HQ isoforms and more LQ isoforms.

**Comment by RobinQi** [comment]
OK, thanks.
