### ISSUE TITLE
Iso-seq analysis help required 

### ISSUE THREAD

**Issue by cchan2014** [PacificBiosciences/cDNA_primer#5]
Our customer got a fusion finder data using below commend line.
“# fusion_finder.py --input Nat_9_quivered_hq.fastq --fq -s Nat_9_quivered_hq.fastq.sorted.sam -o Nat_9_quivered_hq.fusion”
But during the analysis, she found overlapped fusion gene, even different PBfusion ID.
PBfusion.116 c60553/f5p3/803_1-2kb,c28075/f1p1/727_1-2kb,c59562/f2p2/800_1-2kb
PBfusion.154 c60553/f5p3/803_1-2kb,c28075/f1p1/727_1-2kb,c59562/f2p2/800_1-2kb
PBfusion.190 c60553/f5p3/803_1-2kb,c28075/f1p1/727_1-2kb,c59562/f2p2/800_1-2kb

So we checked the reason of this problem and found cluster group with same gene in *.group.txt.
Normally, she thought every PBfusion ID has each unique fusion gene candidate.But now, she is worrying whether she is doing right.
Could you help this issue?
I have attached rep.fq file and you can download input file.

http://data.macrogen.com/RNA_Seq/201505/isoseq/Nat_9_quivered_hq.fastq
http://data.macrogen.com/RNA_Seq/201505/isoseq/Nat_9_quivered_hq.fastq.sorted.sam

**Comment by Magdoll** [comment]
Hi,
The current fusion_finder.py has a bug. I have fixed it but it currently resides in a differnt branch that remains to be merged. 

In the meantime, please download just the fusion_finder.py bug fix version and cover it over the old file:
https://github.com/PacificBiosciences/cDNA_primer/blob/dalign/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/fusion_finder.py

The results from running the fixed fusion_finder.py on your dataset is availble at:
https://www.dropbox.com/sh/74j1twj2b5onx4p/AAByo4Ejss-3Q7dm_oVsX4bEa?dl=0

Please let me know if you find any additional bugs. Thanks!

I will try to upload the fusion_finder.py corrected version to master ASAP.

**Comment by MDxK** [comment]
Our customer checked the data with fixed fusion_finder.py and it seems the problem was solved.

But before the fix, she got 247 candidate fusion gene but after fixed, she found 408 candidate fusion gene. 195 candidate fusion gene was overlapped.

So she wants to know which  number is correct.
And wants to know the reason of different number of candidate .

If possible, please share the log of fixed script.

**Comment by Magdoll** [comment]
Hi,
The older version incorrectly collapsed fusion transcripts that overlapped by had different isoform structures. The new version preserves the differences.

So it is expected that the new version will contain more fusion candidates, however many of them may be the same gene1 - gene2 fusions, just different isoforms. 

If you do a diff of the old versus new fusion_finder.py, you should be able to see the differences.

**Comment by Magdoll** [comment]
The updated fusion_finder.py is now available in version 2.1.0.
