### ISSUE TITLE
Error : pbtranscript.py classify No full-length non-chimeric reads detected

### ISSUE THREAD

**Issue by Dongxn** [PacificBiosciences/cDNA_primer#50]
Hi, 
I am running pbtranscript.py classify and came to an error message that never met：

2016-10-08 10:23:56,388 [INFO] Checking input files.
2016-10-08 10:23:56,389 [INFO] Creating output directory /home/classifyOut.
2016-10-08 10:23:56,389 [WARNING] Output directory /home/classifyOut already exists.
2016-10-08 10:23:56,390 [INFO] checking for phmmer existence.
2016-10-08 10:23:56,420 [INFO] Start to find and trim 3'/5' primers and polyAs.
2016-10-08 10:23:56,421 [INFO] Process primers for finding primers.
2016-10-08 10:23:56,422 [INFO] Primer F1, R1 are reverse complementarily identical. Need to add 'AAAA' to 3' to distinguish them.
2016-10-08 10:23:56,423 [INFO] reuse_dom = False
2016-10-08 10:24:06,314 [INFO] Start to launch phmmer on chunked reads.
2016-10-08 10:27:34,404 [INFO] Get the best front & back primer hits.
2016-10-08 10:27:34,427 [INFO] Trim bar code away from reads.
2016-10-08 10:27:40,129 [INFO] Done with finding and trimming primers and polyAs.
2**016-10-08 10:27:40,133 [ERROR] No full-length non-chimeric reads detected.**
2016-10-08 10:27:40,133 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/analysis/bin/pbtranscript.py", line 117, in run
    obj.run()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Classifier.py", line 937, in run
    raise ClassifierException(no_flnc_errMsg)
ClassifierException: command: classify raised the following error: No full-length non-chimeric reads detected.

**my script looks like:
$cat run.sh**
source /smrtanalysis/etc/setup.sh && pbtranscript.py classify reads_of_insert.fasta isoseq_draft.fasta  --cpus 10  --flnc isoseq_flnc.fasta  --nfl isoseq_nfl.fasta -d=./classifyOut --report=isoseq_primer_info.csv --summary=classify_summary.txt  --min_seq_len=300 

**the reads_of_insert.fasta looks like:
$less reads_of_insert.fasta**
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/8/ccs
TGTCAACGATACGCTACGTAACGGCATGACAGTGTTTTTTTTTTTTTTTTTTCTCACCAGGCTCTTGCCA
AAAGATCCCAACCAACATGGTTGTCCTAGCTCGGGAGATGAACTTTGGAGATAATCTCCATGCGACACGC
CCCGAACGTCTCTGCCTGGAGCTCAGAAGCACTTGCGGTGCACGATGGTGGGGCCAGACTCGTCGTACTC
GCCCTTGGAAATCCACATTTGTTGGAATGTGCTCAAGGACGACAGGATGGATCCGCCGATCCACACCGAG
TATTTGCGCTCGGGCGGGGCCACAACCTTGATCTTCATCGTCGAGGGAGCCAGGGCTGTGAGCTCCTTGG
TCATGCGCTCGCCGATGCCCGCGAACATGGTCGTGCCTCCGGACAGCACAACGTTTGAGTAGAGATCCTT
GCGGATGTCCACGTCGCACTTCATGATGGACTGGAAGGTCGTGTCGTGGATGCCCGCGGCCTCCTTTCCG
ATGAAGCTCGGCTGGAAGAGTACCTCTGGGCAACGGAAGCGCTCACTGCCAACGGTGATGATGTTGCCGT
CGGGCAATTCGTAGGTTTTCTCCTTGTCGGAACTTTCCGTAGCCTGTTTCATCTCCGTGTCGTAATCCAG
AGCAATGTACGAGAGCTTCTCCTTCACGTCGCGCACAATCTCGCGCTCAGCGGTCGTGGTGAACGAGTAG
CCACGCTCAGTCAAGATCTTCATCATGTACTCGGTGAGGTCGCGACCAGCCAAATCCAAGCGCATGATGG
CATGGGGCAGGGCGTAACCCTCGTAGATGGGCACCGTGTGCGACACGCCATCGCCGGAATCCATCACAAT
GCCCGTGGTGCGGCCCGAGGCGTACAGGGACAGCACGGCCTGGATGGCAACATACATAGCAGGAACGTTG
AAGGTCTCGAACATGATCTGGGTCATGCGCTCGCGGTTGGCCTTGGGGTTGAGCGGAGCCTCCGTCAGCA
GTACTGGGTGCTCCTCAGGAGCCACACGCAACTCGTTGTAGAACGTGTGGTGCCAGATCTTCTCCATGTC
GTCCCAGTTCGTCACAATACCGTGCTCAATGGGGTACTTGAGCGTCAGAAACACCACGCTTGCTCTGGAC
CTCGTCACCCACGTAGCTGTCCTTCTGGTCCATGCCAACCATGATGCCAGGCATCTTGGGCCTGCCAACG
ATGGACGGGAAGACAGCTCGTGGGGCGTCGTCGCCCGCGAATCCAGCCTTGCACATTCCCGAGCCGTTGT
CCACCACCAGGGCGGCGACCTCATCCTCATCGGCCATGGCTGGCTATGTCAAGGAAGACGTGTGCTTTCT
ATGCAGGTCGCTGTCTGAGCTTGAGCCAAAATGGCTACGG
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/11/ccs
........

**$grep ">" reads_of_insert.fasta | head**
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/8/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/11/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/17/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/20/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/23/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/24/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/25/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/26/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/27/ccs
>m160925_133439_42278_c101091882550000001823245403091741_s1_p0/29/ccs

**Comment by ylipacbio** [comment]
Seems like there is no full-length non-chimeric ccs reads detected. Would you please post `classify_summary.txt`?

**Comment by Dongxn** [comment]
Hi, ah it seems no summary.txt generated, just got these files in ./classifyOut, I think may be there is something wrong with my reads_of_insert.fasta file. 
$ ll classifyOut/
-rw-r--r-- 1 d k         0 Oct  8 10:32 fl.trimmed.fasta
-rw-r--r-- 1 d k     92457 Oct  8 10:32 hmmer.front_end.dom
-rw-r--r-- 1 d k 132453756 Oct  8 10:33 nfl.trimmed.fasta
-rw-r--r-- 1 d k   6243250 Oct  8 10:33 primer_report.nfl.csv
-rw-r--r-- 1 d k       150 Oct  8 10:29 primers.front_end.fa

**Comment by Dongxn** [comment]
Hi, thank you for your kind answer, this is part of my reads_of_insert.fasta file, I compared it with other reads_of_insert.fasta files I run before, there seems no difference

[reads_of_insert.fasta.txt](https://github.com/PacificBiosciences/cDNA_primer/files/517456/reads_of_insert.fasta.txt)

**Comment by ylipacbio** [comment]
I called pbtranscript classify on the fasta file you provided, and found NO primer was detected. 

Either you have used customer primers in the cDNA sample or something wrong with sequencing of this chip. If you have used customer primers, please specify it via option '--primer YOUR_PRIMER_FILE'.

**Comment by Dongxn** [comment]
thank you ylipacbio, it seems to  be something wrong with my sequencing of this chip, I will check it, if I could get primer information from reads_of_insert.fasta?

**Comment by ylipacbio** [comment]
Please read more about primers [here](https://github.com/PacificBiosciences/cDNA_primer/wiki/Understanding-PacBio-transcriptome-data).

We just could not find any officially supported primer sequences in any reads in reads_of_insert.fasta.

**Comment by Magdoll** [comment]
@Dongxn  if you have been using custom (not Clontech SMARTer) primers for this dataset, it needs to be supplied via command line or UI. If you did use Clontech, then this appears to be a sample prep issue. I'm leaving the issue open for now.

**Comment by Dongxn** [comment]
thank you! I  confirmed it with laboratory staff, it did caused by a wrong  sample prep
