### ISSUE TITLE
call perl in smartshell

### ISSUE THREAD

**Issue by Dongxn** [PacificBiosciences/cDNA_primer#52]
Hi, I 'm using a modified python program of TOFU, in which I  call a perl script in it, 
it seems not using "/share/nas2/genome/bin/perl " but a smart-perl instead, could I change that?
Thank you !

(python_virtualenv)(smrtshell-2.3.0) [dongxn@hpc03-c-0-11 tmp]$ /share/nas2/genome/bin/perl /share/nas1/dongxn/bin/program/PacBio/v1.4/bin/gmap_split_fq.pl
Use of uninitialized value $mask in vec at /share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/miscdeps/basesys/usr/lib/perl5/5.8.8/warnings.pm line 344.
/share/nas2/genome/bin/perl: symbol lookup error: /share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/miscdeps/basesys/usr/lib64/perl5/5.8.8/x86_64-linux-thread-multi/auto/Data/Dumper/Dumper.so: undefined symbol: Perl_Tstack_sp_ptr

**Comment by mhsieh** [comment]
We do not expect people to use PERL inside the smrtshell, but if you really need to run your PERL program outside of smrtshell, here is the replacement string for your perl.

`env -u PERLLIB -u PERL5LIB /share/nas2/genome/bin/perl`

Let's hope that smrtshell's LD_LIBRARY_PATH doesn't interfere your /share/nas2/genome/bin/perl and you don't need PERLLIB and PERL5LIB variables.
