### ISSUE TITLE
matchAnnot.py error

### ISSUE THREAD

**Issue by Dongxn** [PacificBiosciences/cDNA_primer#55]
Hi, I have run matchAnnot.py in one of my projects, and came to an error meassage that never appeared before:  

[2016-10-12 18:15:57] check gft file contains the sam item or not
 Analysis start...
[2016-10-12 18:16:08] check.sam.pl Analysis end...
[DEBUG] 2016-10-12 18:22:25,179 [Annotations 13] version 20150611.01 loaded
[DEBUG] 2016-10-12 18:22:25,217 [Cluster 13] version 20150814.01 loaded
[DEBUG] 2016-10-12 18:22:25,253 [ClusterReport 11] version 20141029.01 loaded
[DEBUG] 2016-10-12 18:22:25,350 [CigarString 15] version 20150707.01 loaded
[DEBUG] 2016-10-12 18:22:25,367 [PolyA 17] version 20150402.01 loaded
[DEBUG] 2016-10-12 18:22:25,367 [matchAnnot 37] version 20150611.02 starting
[DEBUG] 2016-10-12 18:22:25,368 [Annotations 134] reading annotations in standard format from /C77/genome/Spurpurea_289_v1.0.gene_exons.gtf
[DEBUG] 2016-10-12 18:22:36,709 [Annotations 213] read 37865 genes, 61520 transcripts, 388749 exons
[DEBUG] 2016-10-12 18:22:36,711 [matchAnnot 60] reading SAM file ./MatchAnno/all_sizes.sorted.5merge.collapsed.rep.fa.sorted.sam.P.sam
Traceback (most recent call last):
  File "/SMRT/MatchAnnot-master/matchAnnot.py", line 541, in <module>
    main()
  File "/SMRT/MatchAnnot-master/matchAnnot.py", line 118, in main
    cigar = cs.CigarString(cigarString, start, match.group(1))
  File "/SMRT/MatchAnnot-master/CigarString.py", line 79, in **init**
    self.expandCigarString()           # add substitution errors to cigar string
  File "/SMRT/MatchAnnot-master/CigarString.py", line 300, in expandCigarString
    raise RuntimeError ('mismatching field length at %d in MD string %s' % (strIx, MD))
RuntimeError: mismatching field length at 19 in MD string 21C22T31A5A5T16A59^GTCCCATGTAATTTACTGATTATGCCTCAATTAGTTTAATAAGTTATA2AAA3C2A1A3T1GTC8TAT2T1ATG3TCA1A3G2A2C2TC2GA24A43^A34A30^GT0G27G13G70A15C122G109T8G5G77T15A16^GT8A55A11T83T21G49A40A11^A42TGAC20T15A44T25C6C6^T12T5A19G53^TCT38C38^TTAGCAC6A92T39T1AG61A8G76A68G8G20A3C11A21C14A23C7A9T46A17A16C8C30T1T2A8A24A64A96C37T88A63A111G176A5A180A65A102G118C51T23C52G68^TTGG46T4

 I don't really understand the error message, it seems something wrong with the sam file...

**Comment by Magdoll** [comment]
This looks like a SAM file format error. matchAnnot does have a few bugs that don't properly handle SAM files well, to trouble-shoot, I would:

(1) first, re-run the SAM file again. Make sure the SAM file is successfully completed. Run matchAnnot. If error is still re-produced, the problem is with matchAnnot. 

(2) if confirm issue is with matchAnnot, please send over the SAM file and the GTF. I'll email the matchAnnot author to see if he can deal with it (he recently retired). If he can't, I'll troubleshoot it.

--Liz

**Comment by Dongxn** [comment]
[error.sam.txt](https://github.com/PacificBiosciences/cDNA_primer/files/535596/error.sam.txt)

Hi, thank you Magdoll. I just delete the error sequence in sam file, and continue run matchAnnot.py , it works.
Here is the sequence.
