### ISSUE TITLE
How to remove PCR chimeras?

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#57]
Hello,
Now I have used Iso_seq pipline to get FLNC. But I find some FLNC reads are PCR chimeras (https://github.com/PacificBiosciences/cDNA_primer/wiki/Artificial-concatemers,-PCR-chimeras,-and-fusion-genes#pcr), here is the  PCR chimeras example:
5’ primer(TTTT)n( Transcript 1, partial, reversed)( Transcript 2, partial )(AAA)n 3’ primer
Is there any script can remove the PCR chimeras?

Thanks a lot !

**Comment by Magdoll** [comment]
There's no certain way to remove PCR chimera, only some hacks (with caveats, of course).

One way is to remove any FLNC read (or resulting HQ isoform) that have more than a certain number of "T"s in the beginning. This is usually an indication that it is a PCR chimera. Downside you may lose actual real isoforms that do naturally start with a T stretch. 

You could also further confirm this by mapping it to the genome, and only remove those isoforms that map chimerically to the genome *and* also have the polyT stretch. This way you likely preserve any real fusion transcripts (which would map chimerically, but would not have the polyT stretch) while removing most of the PCR chimeras.

A third way that I have used, is if you have Illumina data, map it to the HQ isoforms using BowTie2 (or other short read aligners) using as relaxed an option (allowing max number of mismatches and reporting all multi-mappings using the --all option), then require that all HQ isoforms must have at least 1X coverage throughout the transcript. I find this to be effective at identifying the PCR chimeras. Real biological fusion transcripts would have continuous short read coverage, whereas a PCR chimera would not.

Hope this helps.

--Liz
