### ISSUE TITLE
collapse_isoforms_by_sam.py error

### ISSUE THREAD

**Issue by aechchiki** [PacificBiosciences/cDNA_primer#58]
Hi guys. 

I am trying to run  `collapse_isoforms_by_sam.py` from within a virtual environment, as described in the readme. However, I got an error on execution.

Here is my exact command-line: 

`/home/aechchik/wgets/cDNA_primer/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/collapse_isoforms_by_sam.py --input isoseq.fasta -s isoseq_gmap_sort.sam`

(Note: `isoseq.fasta` is the (non furtherly corrected) final high-quality isoforms from iso-seq pipeline; `isoseq_gmap_sort.sam` is the sorted mapping file generated in the previous step (with gmap), using the tofu tutorial.)

Here is my log:
```
Traceback (most recent call last):
  File "/home/aechchik/wgets/cDNA_primer/pbtranscript-tofu/pbtranscript/pbtools/pbtranscript/collapse_isoforms_by_sam.py", line 40, in <module>
    from pbtools.pbtranscript.Utils import check_ids_unique
  File "/tmp/virtualenv-1.11.6/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/__init__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/tmp/virtualenv-1.11.6/lib/python2.7/site-packages/pkg_resources/__init__.py", line 26, in <module>
    import zipfile
  File "/software/lib64/python2.7/zipfile.py", line 501, in <module>
    class ZipExtFile(io.BufferedIOBase):
AttributeError: 'module' object has no attribute 'BufferedIOBase'
```

Thanks in advance for your help, 
Amina

**Comment by Magdoll** [comment]
Hi,

It appears you are trying to directly execute the script from the repository. Please do not do that as it causes library issues as you see here.

Instead, follow the [installation tutorial](https://github.com/PacificBiosciences/cDNA_primer/wiki/Setting-up-virtualenv-and-installing-pbtranscript-tofu) and use the executable script installed in the virtualenv bin.

If installation is successful in the virtualenv, you should be able to directly run `collapse_isoforms_by_sam.py --input isoseq.fasta -s isoseq_gmap_sort.sam`.

You can test this by typing on the command line:

`$ which collapse_isoforms_by_sam.py`

and verify it's calling it from your virtualenv bin.

**Comment by pb-cdunn** [comment]
Also possible (if you use the right Python):

    python -m pbtranscript.collapse_isoforms_by_sam --input isoseq.fasta -s isoseq_gmap_sort.sam

**Comment by aechchiki** [comment]
thanks @Magdoll, indeed it is working when calling the version in virtualenv, did not pay attention. @pb-cdunn solution also works fine. 
closing the issue.
