### ISSUE TITLE
Segmental Duplications and Isoform-sequencing

### ISSUE THREAD

**Issue by sjin09** [PacificBiosciences/cDNA_primer#68]
To whom it may concern,

I was wondering whether genes that have been copied through segmental duplications (>90% identity and >1kb) can be distinguished during the isoform-sequencing pipeline or whether they are currently indistinguishable because of the 85% accuracy. 

Since the genes have such high identity, I would assume that the transcripts from these genes would be also highly similar and this might cause the erroneous clustering or consensus-calling during the processing. These genes are also of high interest as segmental duplications have shown to generate new genes with new functions.

Best,
Sangjin Lee

**Comment by Magdoll** [comment]
We recently had another group looking at segmental duplicated genes using Iso-Seq. They were also > 90% identity (I think it was an average of 95-99% identity) and found that most of the cluster results were well-distinguished. They did find handful cases where the cluster did collapse the duplicated genes.

Note that even though raw accuracy is 85%, the input that goes into Iso-Seq clustering (ICE + Quiver) is FLNC (CCS reads). For transcripts < 3 kb this would mean way above 85% accuracy, most likely in the 95-99% accuracy range, so ICE would be able to well distinguish them. Also note that lower accuracy would in fact, not cause them to be clustered together, but rather the opposite -- lower accuracy is more likely to show differences in alignments and be rejected by ICE as being in the same cluster. 

That being said, I think the best sanity check is to:
(1) align the post-cluster (HQ isoforms)
(2) align the FLNC (what goes into cluster)

visualize a few key genes of interest. If you see a pattern of widespread mis-clustering, please let me know and we can devise strategies to handle this either through tightening ICE's clustering parameters or analyzing directly through FLNC for the select duplicated genes.

--Liz

**Comment by sjin09** [comment]
That is great to hear! Thank you so much for the detailed response. I will get back if there any signs of such mis-clustering!

**Comment by sjin09** [comment]
Dear @Magdoll 

I wanted to test how difference references for the same organism impacts the isoform-representation. 

For example, reference A and reference B exists. The reference B was recently assembled with using Falcon and subreads from the RSII with P6C4 chemistry. We have sequenced the transcriptome of the B organism as well with the SMRT platform. We have realized that when we align the transcriptomes (high quality transcripts) to the A and B references and collapse them with ToFU there would be reference bias in terms of mapping and collpasing. In other words, the same transcript may be represented differently by the two references in the presence of structural variations.

We thought that COGENT might provide a reference-free approach to obtain non-redundant transcripts. We were planning to obtain the full coding sequence using COGENT, realign the transcripts that were used in that process and collapse them using ToFU to obtain non redundant transcripts. It seems in the preliminary manuscript that highly similar genes such as MYH6 and MYH7 can be erroneously mixed together. The genes that are highly similar as a result of segmental duplications are of high interest to our research. 

Under these considerations, I wanted to ask two questions:

1. What are your thoughts on our approach? Would there be much drawback?
2. Could you suggest any parameter optimization for COGENT for erroneous clustering between two or multiple highly similar genes?

I look forward to hearing from you

**Comment by Magdoll** [comment]
Hi @sjin09 ,

Indeed using Cogent as a reference-free approach to collapse would be a good idea! I have done so with a few samples that had either no reference genomes or poor reference genomes and it had been very helpful with identifying missing or broken gene loci in the genomes. 

Your concern about collapsing highly homologous genes like MYH6 and MYH7 is valid. There are several parameters in Cogent that would allow changing the family finding (clustering) algorithm and the later reconstruction part.

For the family finding part, the parameter is `--ncut_threshold`, which by default is 0.2. The ncut module is this one (http://scikit-image.org/docs/dev/auto_examples/segmentation/plot_ncut.html) and the ncut_threshold is the normalized threshold of sum edge weights that go in between two clusters. A larger ncut threshold should result in more clusters, possibly separating homologs, but also at the risk of unnecessarily further dividing a same gene into separate clusters. I would suggest picking perhaps a pair of genes (the analog of MYH6-MYH7 in your species) and track which clusters they go to when you change `--ncut_threshold`.

Still, even if homologous genes are put into the same cluster (a gene "family"), I would run reconstruction as is to see if it generates a single reconstructed output (in output file `cogent2.fa`) vs multiple. Currently parameters for reconstruction are mostly hard-coded, but given sufficient examples, I can start making these parameters accessible to users. 


re: paper --- I actually just updated the paper using larger datasets (which sadly removed the original example that had the MYH6-MYH7 one, sorry, I was trying to generalize the alg. to larger whole transcriptome datasets and being more rigorous about validation and comparison against other tools). 

in case you are interested the links are here for [paper](https://www.dropbox.com/s/kz0gi7qg0w82k9a/20161026_Cogent_manuscript_forGitHub.pdf?dl=0) and [supplement](https://www.dropbox.com/s/37412o8glvnfhf9/20161026_Cogent_ManuscriptPlusSupplement_forGitHub.pdf?dl=0)

I'll keep in mind the MYH6-MYH7 test case. Eventually I would hope to have Cogent be sensitive enough to distinguish them, but I need more examples to train on.

--Liz

**Comment by sjin09** [comment]
I think if you require larger datasets these papers would be of interest to you. The first paper "de novo assembly and phasing of a Korean human genome" has 1-2kb, 2-3kb, 3-6kb and 5kb libraries and each library was sequenced 6 times with the P6C4 on RSII. The second paper "long-read sequencing and de no vo assembly of a Chinese genome" also released 50 SMRT cell worth of data.

http://www.nature.com/nature/journal/v538/n7624/full/nature20098.html
http://www.nature.com/articles/ncomms12065

Best
Jin

**Comment by Magdoll** [comment]
Hi @sjin09  thanks for pointing out the dataset. Importantly, though, I would want some domain knowledge of what genes to even look for that would have HSD. I suppose I can just go look for a list of them :)

--Liz

**Comment by sjin09** [comment]
I think this paper then "The evolution and population diversity of human-specific segmental duplications" (http://www.nature.com/articles/s41559-016-0069?WT.feed_name=subjects_genomic-analysis) then would be of interest to you. They catalog a number of genes that are thought to be uniquely duplicated in the human population.

**Comment by sjin09** [comment]
I was able to install and run COGENT, but reconstruct_contig.py were unsuccessful for some of the directories.

```
Traceback (most recent call last):
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/bin/reconstruct_contig.py", line 4, in <module>
    __import__('pkg_resources').run_script('Cogent==1.6', 'reconstruct_contig.py')
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 318, in <module>
    main()
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 252, in main
    run_Cogent_on_input()
  File "/mnt/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/EGG-INFO/scripts/reconstruct_contig.py", line 210, in run_Cogent_on_input
    sp.reachability(G, mermap, {}, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 286, in reachability
    reachability_helper(G, source, [], visited, mermap, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 320, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), [cur], visited, mermap, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 312, in reachability_helper
    reachability_helper(G, n, [], visited, mermap, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 314, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 314, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 314, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 314, in reachability_helper
    reachability_helper(G, G.successors_iter(cur).next(), chain + [cur], visited, mermap, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 298, in reachability_helper
    collapse_chain(G, chain+[cur], mermap, path_d)
  File "/ruby/PacBio/Project/AK1/ASIAN_GENOME/SangJin/01.AK1/python/envs/anaCogent/lib/python2.7/site-packages/Cogent-1.6-py2.7.egg/Cogent/splice_graph.py", line 271, in collapse_chain
    assert oldp[j] in (n0, nlast)
AssertionError

```

I was wondering if you could provide any clues towards debugging this or are we supposed to ignore the directories where reconstruct_contig.py are unsuccessful?

Best,
Jin

**Comment by Magdoll** [comment]
Hi @sjin09 ,

Yes there are still some bugs in Cogent that need to be fixed on a case-by-case basis. 

Can you please file a bug in https://github.com/Magdoll/Cogent/issues? If possible, I will need the input that caused this error (input.fa). If you cannot share it publicly but can share it privately, please email it to etseng@pacb.com.

Thanks,
-Liz

**Comment by sjin09** [comment]
I have sent the relevant files with my email. I hope they have arrived safely. Thanks for all the help! I look forward to your response!

Best,
Jin

**Comment by Magdoll** [comment]
Hi,

Unfortunately I did not receive the email at etseng@pacb.com! It did not appear in junk mail as well :( could you please re-send to both etseng@pacb.com and magdoll@gmail.com with the email title "Cogent bug"?

--Liz
