### ISSUE TITLE
How To Plot Rarefaction/Saturation Curve to assess the sequencing depth

### ISSUE THREAD

**Issue by linglingtingfei** [PacificBiosciences/cDNA_primer#73]
Hi guys,
I want to get rarefaction curve like the website did [https://github.com/PacificBiosciences/cDNA_primer/wiki/Bioinfx-study:-Sampling-depth%3F-Simulated-rarefaction-curves-based-on-real-data](url) . Could anyone give me some advice? Thank you in advance.

**Comment by Magdoll** [comment]
Hi @linglingtingfei ,

The script used to generate the curves is available in Cupcake. Please see here:

https://github.com/Magdoll/cDNA_Cupcake/wiki/Annotation-and-Rarefaction-Wiki#subsample
